#Author: reuelsicatii@yahoo.cpm.ph
Feature: [Instagram]: LikePost Bot

  #Scenario Description:
  #Given Im a Instagram User
  #When I like a post from /Explore/Tags
  #Then I'll see that I've successfully like it
  @CommentPost @CommentPost_TS01
  Scenario Outline: SharePost_TS01
    Given Im a Instagram User
    When I navigate to "Login"
    And I populate IG01_Username textfield with <Username>
    And I populate IG01_Password textfield with <Password>
    And I click IG01_LogIn button
    Then Ill see that Ive login successfully
    And I wait for 10000 millisecond
    When I navigate to the application exact <PageURL>
    And I wait for 10000 millisecond
    And I click IG03_TopRecentPost button
    And I wait for 3000 millisecond
    And I populate IG03_CommentPost textfield with <Username> for 10

    Examples: 
      | Username         | Password         | PageURL                                                           |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/skincare                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/skincareproducts           |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/philippines                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travel                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/itsmorefuninthephilippines |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/wanderlust                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/photography                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelgram                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/nature                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelphotography          |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instagood                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/beach                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/picoftheday                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instagram                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelblogger              |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makati                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makaticity                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatibased                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatibars                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasay                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/mandaluyong                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasig                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/sanjuan                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/eastwood                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/quezoncity                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatieats                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/photooftheday              |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/cebu                       |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/love                       |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelph                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/adventure                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instatravel                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/manila                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bohol                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/summer                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/vsco                       |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/vacation                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/island                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/palawan                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/igers                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makeup                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makeup                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makeupph                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/authentic                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/nailsph                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/perfume                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuy                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/mnl                        |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/forsaleph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/onlineshop                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bathandbody                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/chanel                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bathandbodyph              |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bathandbodymnl             |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bbw                        |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bathandbodyworksph         |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/JoMalone                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/Minis                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/tarte                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/hourglass                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/minis                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/ph                         |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/buxom                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/chanel                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/Sampler                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bbwph                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/BM13avail                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/igersph                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/igersmanila                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/igerspinoy                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/ph                         |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/manila                     |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pinoy                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/iskolar                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instagood                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instadaily                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/picoftheday                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/adobelightroom             |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuy                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuyph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuyphilippines         |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuyus                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuyusa                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuyshopping            |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/shoppingph                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/shoppingphilippines        |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasabuymnl                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/preorderph                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/authenticph                |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/originalph                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/onhandph                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/onhanditemsph              |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/preloved                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/preloveph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/darkkissph                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/resellerph                 |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/openforresellers           |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/momshies                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/momshie                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/coach                      |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/coachph                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/mkslide                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/mkslideph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/cartersph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/oldnavy                    |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/lacosteph                  |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/preorder                   |
      | glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/importedsale_faqs          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/skincare                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/skincareproducts           |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/philippines                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travel                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/itsmorefuninthephilippines |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/wanderlust                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/photography                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelgram                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/nature                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelphotography          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instagood                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/beach                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/picoftheday                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instagram                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelblogger              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makati                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makaticity                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatibased                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatibars                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasay                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/mandaluyong                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasig                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/sanjuan                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/eastwood                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/quezoncity                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatieats                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/photooftheday              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/cebu                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/love                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/adventure                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instatravel                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/manila                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bohol                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/summer                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/vsco                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/vacation                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/island                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/palawan                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/igers                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makeup                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makeup                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makeupph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/authentic                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/nailsph                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/perfume                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuy                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/mnl                        |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/forsaleph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/onlineshop                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bathandbody                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/chanel                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bathandbodyph              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bathandbodymnl             |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bbw                        |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bathandbodyworksph         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/JoMalone                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/Minis                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/tarte                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/hourglass                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/minis                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/ph                         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/buxom                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/chanel                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/Sampler                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bbwph                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/BM13avail                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/igersph                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/igersmanila                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/igerspinoy                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/ph                         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/manila                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pinoy                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/iskolar                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instagood                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instadaily                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/picoftheday                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/adobelightroom             |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuy                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuyph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuyphilippines         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuyus                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuyusa                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuyshopping            |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/shoppingph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/shoppingphilippines        |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasabuymnl                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/preorderph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/authenticph                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/originalph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/onhandph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/onhanditemsph              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/preloved                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/preloveph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/darkkissph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/resellerph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/openforresellers           |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/momshies                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/momshie                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/coach                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/coachph                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/mkslide                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/mkslideph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/cartersph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/oldnavy                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/lacosteph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/preorder                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/importedsale_faqs          |
