#Author: reuelsicatii@yahoo.cpm.ph
Feature: [Instagram]: LikePost Bot

  #Scenario Description:
  #Given Im a Instagram User
  #When I like a post from /Explore/Tags
  #Then I'll see that I've successfully like it
  @LikePost @LikePost_TS01
  Scenario Outline: SharePost_TS01
    Given Im a Instagram User
    When I navigate to "Login"
    And I populate IG01_Username textfield with <Username>
    And I populate IG01_Password textfield with <Password>
    And I click IG01_LogIn button
    Then Ill see that Ive login successfully
    And I wait for 10000 millisecond
    When I navigate to the application exact <PageURL>
    And I wait for 10000 millisecond
    And I click IG03_TopRecentPost button
    And I wait for 3000 millisecond
    And I click IG03_LikePost button for 10

    Examples: 
      | Username         | Password         | PageURL                                                           |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/skincare                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/skincareproducts           |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/philippines                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travel                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/itsmorefuninthephilippines |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/wanderlust                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/photography                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelgram                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/nature                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelphotography          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instagood                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/beach                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/picoftheday                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instagram                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelblogger              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makati                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makaticity                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatibased                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatibars                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasay                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/mandaluyong                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/pasig                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/sanjuan                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/eastwood                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/quezoncity                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/makatieats                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/photooftheday              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/cebu                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/love                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/travelph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/adventure                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/instatravel                |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/manila                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/bohol                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/summer                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/vsco                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/vacation                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/island                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/palawan                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.com/explore/tags/igers                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/makeup                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/makeup                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/makeupph                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/authentic                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/nailsph                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/perfume                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuy                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/mnl                         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/forsaleph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/onlineshop                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bathandbody                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/chanel                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bathandbodyph               |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bathandbodymnl              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bbw                         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bathandbodyworksph          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/JoMalone                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/Minis                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/tarte                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/hourglass                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/minis                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/ph                          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/buxom                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/chanel                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/Sampler                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/bbwph                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/BM13avail                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/igersph                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/igersmanila                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/igerspinoy                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/ph                          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/manila                      |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pinoy                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/iskolar                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/instagood                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/instadaily                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/picoftheday                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/adobelightroom              |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuy                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuyph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuyphilippines          |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuyus                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuyusa                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuyshopping             |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/shoppingph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/shoppingphilippines         |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/pasabuymnl                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/preorderph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/authenticph                 |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/originalph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/onhandph                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/onhanditemsph               |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/preloved                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/preloveph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/darkkissph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/resellerph                  |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/openforresellers            |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/momshies                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/momshie                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/coach                       |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/coachph                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/mkslide                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/mkslideph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/cartersph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/oldnavy                     |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/lacosteph                   |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/preorder                    |
      | bihakupearlwhite | michaeljemah2017 | https://www.instagram.comexplore/tags/importedsale_faqs           |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/skincare                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/skincareproducts           |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/philippines                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travel                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/itsmorefuninthephilippines |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/wanderlust                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/photography                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelgram                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/nature                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelphotography          |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instagood                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/beach                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/picoftheday                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instagram                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelblogger              |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makati                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makaticity                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatibased                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatibars                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasay                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/mandaluyong                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/pasig                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/sanjuan                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/eastwood                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/quezoncity                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/makatieats                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/photooftheday              |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/cebu                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/love                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/travelph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/adventure                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/instatravel                |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/manila                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/bohol                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/summer                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/vsco                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/vacation                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/island                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/palawan                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.com/explore/tags/igers                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/makeup                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/makeup                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/makeupph                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/authentic                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/nailsph                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/perfume                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuy                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/mnl                         |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/forsaleph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/onlineshop                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bathandbody                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/chanel                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bathandbodyph               |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bathandbodymnl              |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bbw                         |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bathandbodyworksph          |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/JoMalone                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/Minis                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/tarte                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/hourglass                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/minis                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/ph                          |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/buxom                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/chanel                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/Sampler                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/bbwph                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/BM13avail                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/igersph                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/igersmanila                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/igerspinoy                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/ph                          |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/manila                      |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pinoy                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/iskolar                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/instagood                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/instadaily                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/picoftheday                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/adobelightroom              |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuy                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuyph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuyphilippines          |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuyus                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuyusa                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuyshopping             |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/shoppingph                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/shoppingphilippines         |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/pasabuymnl                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/preorderph                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/authenticph                 |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/originalph                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/onhandph                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/onhanditemsph               |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/preloved                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/preloveph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/darkkissph                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/resellerph                  |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/openforresellers            |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/momshies                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/momshie                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/coach                       |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/coachph                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/mkslide                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/mkslideph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/cartersph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/oldnavy                     |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/lacosteph                   |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/preorder                    |
      | Glutagirlph      | Bihaku2020       | https://www.instagram.comexplore/tags/importedsale_faqs           |
